version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        # command: sh -c "npm run build && npm run m:run && npm run start"
        command: sh -c "npm run build && npm run start"
        ports:
            - '3000:3000'
            - '8000:8000'
        volumes:
            - .:/usr/app
        environment:
            NODE_ENV: production
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: pucvagas
            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_DBNAME: pucvagas
        container_name: pucvagas-app
        depends_on:
            - db
            - mongo
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pucvagas
        container_name: pucvagas-postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - '5432:5432'
    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        environment:
            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_DBNAME: pucvagas
        container_name: pucvagas-mongo
        volumes:
            - mongodata:/data/mongo
volumes:
    pgdata:
    mongodata:
